### ISSUE TITLE
Quantifying number of results per category

### ISSUE THREAD

**Issue by xabier** [decidim/decidim-accountability#31]
Categories and sub-categories need to be defined when the participatory process begins, and it is often dificult to foresee what the results will be if the process is genuinely participatory. Thus, the results might end up filling-up categories in a very unbalanced manner. In order to help the assesment of the execution of the results it would be nice to have the number of results (actuations/projects) together with % on the main navigation pannel.

@amaia do you think that is possible?

**Comment by amaia** [comment]
@xabier do you mean in the "home" page that has the cards of all categories? or in the left tree nav when you're seeing a result?
/cc @furilo @martgnz

**Comment by xabier** [comment]
at least on the home page. for the tree nav we might have other options

**Comment by furilo** [comment]
Something like 

![captura de pantalla 2017-06-12 a las 16 55 52](https://user-images.githubusercontent.com/24740/27040009-07697a4c-4f90-11e7-9372-c2fbbd87aa4e.png)

or

![captura de pantalla 2017-06-12 a las 16 54 43](https://user-images.githubusercontent.com/24740/27039952-dc1b30ba-4f8f-11e7-8f46-857f489a00ed.png)

?

(I'm not particularly fond of any, just confirm this is the idea so we can give it another spin)

**Comment by xabier** [comment]
@furilo Fantastic, just let's add to the higher order category (a.k.a. Eje, Eix) also. I like both, whatever is most reponsive.

**Comment by amaia** [comment]
@xabier this is deployed to staging, please check it out

**Comment by amaia** [comment]
Closing this one, @xabier if you see anything wrong please reopen it
