### ISSUE TITLE
Categories not clickable in home page

### ISSUE THREAD

**Issue by carolromero** [decidim/decidim-accountability#32]
In the home page, categories are not clickable, only subcategories.
But some results or projects might be associated to just the top category, so these should be clickable as well in order to navigate all the results:
https://decidim-accountability-staging.herokuapp.com/processes/12/f/67
![imatge](https://user-images.githubusercontent.com/23509895/27041973-e86d7f7a-4f95-11e7-8bdd-7f02c60d5918.png)

**Comment by amaia** [comment]
@carolromero just deployed this change to staging, please have a look

**Comment by carolromero** [comment]
@amaia thanks! closing this issue.
