### ISSUE TITLE
Project Evolution Timeline

### ISSUE THREAD

**Issue by carolromero** [decidim/decidim-accountability#33]
According to the mockups, a project evolution timeline was designed, but it's missing from the current version of the component (or I was not able to find it):
https://projects.invisionapp.com/share/BHB503RZC#/screens/227967880
![imatge](https://user-images.githubusercontent.com/23509895/27042491-66d9f248-4f97-11e7-9752-6228d4d94cb1.png)

**Comment by furilo** [comment]
This has not yet been implemented because we were not going to have it for the PAM. We'll add it to our backlog and inform of ETA.

**Comment by amaia** [comment]
@carolromero this is in staging, to create timeline entries click on the clock icon on each result in the admin panel. 

I tried to put it in the result form, but with they way the code is structured I didn't find a way that worked fine, so I made it like this. It could be refactored in the future to integrate the timeline form into the result form.

**Comment by amaia** [comment]
@carolromero sorry, it's broken for now, results are not being shown inside categories, I think because of some changes on how categories work inside decidim

**Comment by amaia** [comment]
The home page is broken until we merge #42 but the timeline can be tested adding the info in the admin panel and then clicking on the eye icon to see that result page directly

**Comment by carolromero** [comment]
Thanks @amaia and @furilo! I tried it out and works fine:
https://decidim-accountability-staging.herokuapp.com/processes/12/f/67/results/6747
![imatge](https://user-images.githubusercontent.com/23509895/27492840-ebb3429a-5847-11e7-8615-db97f4d773d9.png)

The only suggestion is using another class (maybe `description` instead of `header`)
![imatge](https://user-images.githubusercontent.com/23509895/27492897-12cad1d6-5848-11e7-99bb-5c667bb429ed.png)

**Comment by amaia** [comment]
@carolromero this is up in staging

**Comment by carolromero** [comment]
looks great!! closing this.
