### ISSUE TITLE
Downloadable CSV File on the Front-End

### ISSUE THREAD

**Issue by carolromero** [decidim/decidim-accountability#34]
As a user I might want to download project/result data in a CSV file from the Results home page.
This feature was included in the specs documentation. I didn't see it in the mockups, though.
Is this going to be implemented in the current version?

**Comment by amaia** [comment]
@carolromero where should the link to download the CSV file go?

**Comment by carolromero** [comment]
Hi @amaia not sure where the link should go, I didn't see it in the previous mockups. 
The only info we have is this:
_"La ciudadanía podrá descargar los datos en bruto en CSV. Se analizará el formato idóneo para descargar los datos de modo que fomenten una reutilización efectiva"._

But it seems reasonable to place the link somewhere in the results homepage:
https://decidim-accountability-staging.herokuapp.com/processes/12/f/67
Could you make a proposal of design?

**Comment by amaia** [comment]
@carolromero I've put it below the progress number for now, until @furilo or @martgnz can make a design proposal. 
I've merged the PR #39 and deployed to staging, so you can start testing it and seeing if it's ok. I'll do any changes required in another PR.

**Comment by carolromero** [comment]
Thanks @amaia, I've downloaded the file and everything looks fine.
As for design, to me this solution looks good enough.
Closing this issue by now
