### ISSUE TITLE
Import data CSV - related proposals

### ISSUE THREAD

**Issue by carolromero** [decidim/decidim-accountability#35]
As explained in the [documentation](https://github.com/decidim/decidim-accountability/blob/master/doc/csv_importer.md), you can import data from a CSV file, using the following structure:

```
- result_id
- decidim_category_id
- decidim_scope_id
- parent_id
- external_id
- parent_external_id
- start_date
- end_date
- decidim_accountability_status_id
- progress
- title_ca
- title_es
- title_en
- description_ca
- description_es
- description_en
```
You can also create results from the admin panel manually, and in the process you can select which proposals are related to a given result:
![imatge](https://user-images.githubusercontent.com/23509895/27049760-8c83433c-4fb0-11e7-8bf1-b738123e153f.png)

Thinking about the proposals-results internal workflow, we need a way to link proposals and results  using the CSV importer. An admin will generally download the proposals to a CSV file, work on them and generate the equivalent results. @amaia @furilo any ideas on how can we work this out using the importer?

**Comment by amaia** [comment]
@carolromero I've added a new column to the CSV importer for the proposal_ids. The content for that column should be the list of Proposal IDs separated by semicolons (;)
