### ISSUE TITLE
Adapt styles in admin panel

### ISSUE THREAD

**Issue by carolromero** [decidim/decidim-accountability#36]
In order to keep the consistency of the admin panel design, the management options should follow the same visual styles than the other components. 

An option could be something like this:
![imatge](https://user-images.githubusercontent.com/23509895/27155081-bc5bc36a-5157-11e7-8708-dc44b6e21315.png)

ps. What is the "Results" option for?

**Comment by amaia** [comment]
@carolromero the "Results" option goes to the "home page" of the feature, the same as if you click on the accountability link in the left column menu

**Comment by amaia** [comment]
@carolromero I've moved the links to the title bar and removed the results item, the buttons are a bit close to one another, but that depends on the decidim-core css, as far as I know. 
It's in staging.

**Comment by carolromero** [comment]
@amaia I checked it out and to apply the same logic to all components, I would show the links only in the main page of the component. When you clic on a specific action (eg. create new result, create new status, etc.) the links should be hidden, otherwise it looks a bit confusing:
![imagen](https://user-images.githubusercontent.com/23509895/27297280-80c32688-5524-11e7-806d-724ae425c853.png)

Following the example with Proposals, you have 2 options in the main page: "New Proposal" and "Export":
![imagen](https://user-images.githubusercontent.com/23509895/27298394-ba040b98-5528-11e7-9cd7-f62b9e6a4d5e.png)

and once you clic on "New Proposal" the form looks like this:
![imagen](https://user-images.githubusercontent.com/23509895/27297913-0735af40-5527-11e7-85c7-c3ed32c47221.png)

ps. The usability of the admin interface needs to be globally improved, just trying to keep consistency meanwhile :)

**Comment by amaia** [comment]
@carolromero oops, I forgot to remove it from the new and edit pages, it should be fixed now

**Comment by amaia** [comment]
@carolromero is there anything missing in this issue that needs to be fixed? can we close it?

**Comment by carolromero** [comment]
@amaia it looks ok to me, closing.
