### ISSUE TITLE
Adding and improving Status descriptions

### ISSUE THREAD

**Issue by carolromero** [decidim/decidim-accountability#38]
**Homepage**
In the Results homepage there's an info icon but there's no tooltip or link associated with it. One option is to remove the icon and explain what the "Global Execution" status means in the side description. Otherwise there should be an info field enabled for that matter:
![imagen](https://user-images.githubusercontent.com/23509895/27280915-02cc2de0-54ea-11e7-866f-cf2995f1be53.png)

**Results page**
Also, the status are defined with title and description, but only the title is displayed in the Result page. Adding the description would help the user to understand the follow-up process:
![imagen](https://user-images.githubusercontent.com/23509895/27281510-78499434-54ec-11e7-80be-a9533ed9d76d.png)

**Comment by amaia** [comment]
@carolromero this one is done and staging, please check it out

**Comment by carolromero** [comment]
Reviewed :+1:
