### ISSUE TITLE
Minor design changes in results home page

### ISSUE THREAD

**Issue by arnaumonty** [decidim/decidim-accountability#40]
In order to improve the results homepage, we suggest this three minor changes
- [x] We do not show empty categories or subcategories #43 
- [x] The behavior of links (colors) in subcategories should be the same as categories.
- [x] There is no padding below the percentage when a category is empty the title is two lines long.

cc/ @carolromero @andreslucena @xabier @htmlboy

**Comment by htmlboy** [comment]
Sounds right, but could you provide a screenshot for context?

**Comment by xabier** [comment]
On 26/06/17 18:00, Javier Usobiaga wrote:
> Sounds right, but could you provide a screenshot for context?

check out instances of decidim in https://decidim-monitor.herokuapp.com/

many have the problems and gaps just reported

**Comment by htmlboy** [comment]
I'm sorry but I'm quite lost with this development :-( @arnaumonty, could you post some screenshots of the problems you're addressing? Or point to a specific url?

**Comment by furilo** [comment]
Hey, we are taking care of this small fixes. Probably don't need to worry
@htmlboy ;)
-- 
Álvaro Ortiz
twitter.com/furilo

Populate / Tools for civic engagement
http://populate.tools

Weekly digest of interesting links and project news
getrevue.co/profile/populate

**Comment by xabier** [comment]
@htmlboy sorry, I thought this was something different! My fault!

**Comment by arnaumonty** [comment]
Thanks @furilo  to clarify it!
@htmlboy we are working on [this](https://decidim-accountability-staging.herokuapp.com/processes/12/f/67)

**Comment by amaia** [comment]
@arnaumonty all the changes are deployed to staging, could you check them, please?

**Comment by arnaumonty** [comment]
Great! Everything is ok. Thanks @amaia
