### ISSUE TITLE
Missing embed feature  

### ISSUE THREAD

**Issue by andreslucena** [decidim/decidim-accountability#53]
There is a feature missing from results migration. It's embedding a result, it should be simple to migrate 

# Example of an embedded result: 
* https://www.decidim.barcelona/processes/1/f/8/results/5148?locale=es  
![image](https://user-images.githubusercontent.com/717367/27903630-4c4a85d6-623a-11e7-9021-c742692010db.png)

# Related issue: 
* https://github.com/decidim/decidim/issues/606

# Relevant files 
Searching by embed/widget on decidim-results 
* https://github.com/decidim/decidim/blob/bc59b1a2406a661bce4ef8b621b7ca233b1f9928/decidim-results/lib/decidim/results/engine.rb#L16
* https://github.com/decidim/decidim/blob/8a7a0ab3dbe7f91f04bae762b31fcdc4d35b81f7/decidim-results/app/views/decidim/results/results/show.html.erb#L43
* https://github.com/decidim/decidim/blob/bc59b1a2406a661bce4ef8b621b7ca233b1f9928/decidim-results/app/controllers/decidim/results/result_widgets_controller.rb 
* https://github.com/decidim/decidim/blob/733aad899918d0437de3d1d9e8eed4f9923503ce/decidim-results/app/controllers/decidim/results/results_controller.rb#L8

**Comment by ferblape** [comment]
Ya podéis comprobar en staging que está el embed dentro de la página de resultados. Ejemplo: https://decidim-accountability-staging.herokuapp.com/processes/1/f/66/results/502

**Comment by ferblape** [comment]
Cerrada de acuerdo con @carolromero
