### ISSUE TITLE
CSS from engine is not being included in app

### ISSUE THREAD

**Issue by amaia** [decidim/decidim-accountability#6]
We're running into a weird problem with the loading of CSS files from the engine. 

If we use the dummy app inside the spec directory the CSS from the accountability module loads correctly and we can see the changes in styles. 

But if I try to use the decidim-accountability gem from a clone of the decidim-barcelona repo the accountability css doesn't get included. 

In my clone of decidim-barcelona I've changed the Gemfile to add the decidim-accountability gem like this: 

`gem "decidim-accountability", path: "../decidim-accountability"`

where `../decidim-accountability` is the path where I have this repo cloned.

Everything else seems to be working correctly and I can see the changes that are made in the html and ruby code in the decidim-accountability directory reflected in the app running from decidim-barcelona.

I've pushed a branch with the few changes to use the accountability engine to https://github.com/PopulateTools/decidim-barcelona/blob/accountability-localdev/Gemfile

@josepjaume @oriolgual can you help with this setup, please? What should be the way to use an external decidim gem? Could you also test it locally to see if I've misconfigured anything, please? 

To test, I'm adding some css to the `_results.scss` file  locally like this: 
```
#categories {
  background-color: #fabada;
}
``` 
but I don't see it included in the main css file where all the other css from engines is included.

I've made another test symlinking the decidim-accountability directory inisde the engines directory in decidim-barcelona and changing the path in the Gemfile to `engines/decidim-accountability`and it worked too, but I can't get it to work again now.

**Comment by oriolgual** [comment]
Have you declared the assets and the manifest for the engine? You can look at `decidim-comments` as an example:

https://github.com/decidim/decidim/blob/master/decidim-comments/lib/decidim/comments/engine.rb#L21-L23

https://github.com/decidim/decidim/blob/master/decidim-comments/app/assets/config/decidim_comments_manifest.js

**Comment by amaia** [comment]
@oriolgual we're not using javascript (not yet at least), only CSS, so I haven't done a js manifest

**Comment by amaia** [comment]
@oriolgual I've added this line to feature.rb:

`feature.stylesheet = "decidim/accountability/accountability"`

https://github.com/decidim/decidim-accountability/blob/master/lib/decidim/accountability/feature.rb#L9

**Comment by oriolgual** [comment]
Then it should be working, can you try removing the `tmp` folder so the assets get recompiled?

**Comment by amaia** [comment]
@oriolgual that did it, thank you! I was going crazy with the things not updating when I expected

**Comment by andreslucena** [comment]
@oriolgual can we add this to the docs on https://github.com/decidim/decidim/blob/master/docs/how_to_create_a_plugin.md ?

@amaia just so we know, how do you started the new engine? Using that doc or copy pasting another one?

**Comment by amaia** [comment]
@andreslucena I copied Decidim::Results from https://github.com/decidim/decidim/tree/master/decidim-results and then made some changes based on the How to create a plugin docs
