### ISSUE TITLE
% execution disappears when filtering by scope

### ISSUE THREAD

**Issue by carolromero** [decidim/decidim-accountability#60]
When the scopes are enabled and one of them is selected, the execution progress bar disappears.
An exemple can be seen in the PAM Process:
https://decidim-accountability-staging.herokuapp.com/processes/1/f/66/?filter%5Bcategory_id%5D=&filter%5Bscope_id%5D=9
**No filters by scopes applied**
![imatge](https://user-images.githubusercontent.com/23509895/28361134-0ab2d400-6c78-11e7-8731-2fff4a1698e4.png)

**Filter by scope selected**
![imatge](https://user-images.githubusercontent.com/23509895/28361086-d99ae61e-6c77-11e7-8537-bcba4fea5238.png)

**Comment by ferblape** [comment]
@carolromero I think that's because those results don't have a progress. For example in [Justicia Social](https://decidim-accountability-staging.herokuapp.com/processes/1/f/66/results?filter%5Bcategory_id%5D=2&filter%5Bscope_id%5D=9) none of the four results have a progress.
