### ISSUE TITLE
Support different number of results levels

### ISSUE THREAD

**Issue by furilo** [decidim/decidim-accountability#7]
As we’re going to use this module for the MetaDecidim process as well as the PAM process, an potentially also for other processes, we need to also support having different levels in results.
For example:

PAM:
Category (Eje) -> Subcategory (Linea) -> Result (Actuación) -> Project

MetaDecidim:
Category -> Subcategory -> Result (with all the info of a project: start date, end date, status, progress)

And we could also have:
Category -> Result (with all the info of a project: start date, end date, status, progress)

That would mean that the information that now is stored in the Project model (start date, end date, status, progress) would also have to be available one level up in Result. So we’ve thought that we could merge the current Result and Project models, and have the start date, end date, status, progress fields in the new merged Result model, and allow to create a Result as a child of another Result (only 2 levels, like categories). And also have validations to make the information consistent and always have the same entities per level in a given process feature.

For example, if a Result has values in the dates and status fields, it can’t have children, and this data would be shown in the list in the public views, and link to the result page with all the info. If it has children it would show the number of children and a link to the next level list.

What do you think @oriolgual @josepjaume @andreslucena @xabier ?

**Comment by xabier** [comment]
> That would mean that the information that now is stored in the Project model (start date, end date, status, progress) would also have to be available one level up in Result. So we’ve thought that we could merge the current Result and Project models, and have the start date, end date, status, progress fields in the new merged Result model, and allow to create a Result as a child of another Result (only 2 levels, like categories). And also have validations to make the information consistent and always have the same entities per level in a given process feature. For example, if a Result has values in the dates and status fields, it can’t have children, and this data would be shown in the list in the public views, and link to the result page with all the info. If it has children it would show the number of children and a link to the next level list.

I like this option a lot. @andreslucena @josepjaume we are defining a "new" component here, with its own settings and additional features. I think it will work good.

**Comment by oriolgual** [comment]
Nice approach @furilo!
